server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 60.205.214.254
      port: 8500
      discovery:
        service-name: ${spring.application.name}